# Generated by Django 4.0.5 on 2022-06-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('slug', models.SlugField(max_length=512)),
                ('level_id', models.PositiveSmallIntegerField()),
                ('icon', models.CharField(blank=True, default='', max_length=512)),
                ('slider_image', models.CharField(blank=True, default='', max_length=512)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_categories.productcategory')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
    ]
