# Generated by Django 4.0.6 on 2022-07-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Product Categories'},
        ),
    ]
