# Generated by Django 4.0.2 on 2022-05-29 20:30

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(null=True, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('brand', models.CharField(max_length=128, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('currency', models.CharField(choices=[(products.models.CurrencyChoice['Pound'], 'Pound'), (products.models.CurrencyChoice['Dollar'], 'Dollar'), (products.models.CurrencyChoice['Euro'], 'Euro')], default=products.models.CurrencyChoice['Euro'], max_length=32)),
                ('slug', models.CharField(default='', max_length=1024)),
                ('min_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('max_price', models.DecimalField(decimal_places=4, max_digits=19)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
