# Generated by Django 4.0.2 on 2022-06-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
