# Generated by Django 4.0.2 on 2022-06-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_groups', '0002_alter_productgroup_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['-created_at']},
        ),
    ]
