# Generated by Django 4.0.2 on 2022-06-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_groups', '0004_productgroup_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={'verbose_name_plural': 'Product Groups'},
        ),
    ]
