# Generated by Django 4.0.5 on 2022-07-08 18:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product_groups', '0005_alter_productgroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
