# Generated by Django 4.0.6 on 2022-07-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_groups', '0006_alter_productgroup_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Product Groups'},
        ),
    ]
