# Generated by Django 4.0.2 on 2022-06-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_description_shopworkfield_shop_work_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='shopworkfield',
            options={'ordering': ['-created_at']},
        ),
    ]
