# Generated by Django 4.0.2 on 2022-06-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_remove_shop_work_field_shop_work_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterModelOptions(
            name='shopworkfield',
            options={'verbose_name_plural': 'Shop Work Fields'},
        ),
    ]
