# Generated by Django 4.0.5 on 2022-06-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0001_initial'),
        ('shops', '0006_alter_shop_options_alter_shopworkfield_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopworkfield',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product_categories.productcategory'),
        ),
    ]
