# Generated by Django 4.0.6 on 2022-07-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_shopworkfield_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterModelOptions(
            name='shopworkfield',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Shop Work Fields'},
        ),
    ]
