# Generated by Django 4.0.2 on 2022-06-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDiscover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('link', models.URLField(max_length=2048)),
                ('image', models.CharField(blank=True, default='', max_length=2048)),
                ('background_image', models.CharField(blank=True, default='', max_length=2048)),
                ('button_title', models.CharField(default='Discover', max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
