# Generated by Django 4.0.2 on 2022-06-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homediscover',
            options={'verbose_name_plural': 'Home Discovers'},
        ),
    ]
