# Generated by Django 4.0.6 on 2022-07-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovers', '0002_alter_homediscover_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homediscover',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Home Discovers'},
        ),
    ]
