# Generated by Django 4.0.2 on 2022-02-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('price', models.FloatField(max_length=256)),
                ('link', models.CharField(max_length=2048)),
            ],
        ),
    ]
