# Generated by Django 4.0.2 on 2022-02-27 19:43

import django.contrib.postgres.fields
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[(products.models.CurrencyChoice['Pound'], 'Pound'), (products.models.CurrencyChoice['Dollar'], 'Dollar'), (products.models.CurrencyChoice['Euro'], 'Euro')], default=products.models.CurrencyChoice['Euro'], max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='original_image',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=32),
        ),
    ]
