# Generated by Django 4.0.2 on 2022-02-28 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('products', '0002_product_currency_product_discount_product_enable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='shops.shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(max_length=2048),
        ),
    ]
