# Generated by Django 4.0.2 on 2022-03-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=512),
        ),
        migrations.DeleteModel(
            name='DigitalCategory',
        ),
    ]
