# Generated by Django 4.0.2 on 2022-03-04 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_slug_delete_digitalcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_crawl_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
