# Generated by Django 4.0.2 on 2022-03-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product'),
        ),
    ]
