# Generated by Django 4.0.2 on 2022-03-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productview_count_alter_productview_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.CreateModel(
            name='ProductPriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('discount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
