# Generated by Django 4.0.2 on 2022-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_groups', '0001_initial'),
        ('products', '0014_remove_product_last_crawl_time_productcrawllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='groups',
            field=models.ManyToManyField(related_name='products', to='product_groups.ProductGroup'),
        ),
    ]
