# Generated by Django 4.0.2 on 2022-06-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_category_icon_alter_category_slider_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productcrawllog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productpricelog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productview',
            options={'ordering': ['-created_at']},
        ),
    ]
