# Generated by Django 4.0.2 on 2022-06-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='productcrawllog',
            name='crawl_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
