# Generated by Django 4.0.2 on 2022-06-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_color_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productview',
            name='session_id',
        ),
        migrations.AddField(
            model_name='productview',
            name='client_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
    ]
