# Generated by Django 4.0.2 on 2022-06-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_remove_shop_work_field_shop_work_fields'),
        ('products', '0021_alter_category_description_alter_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
    ]
