# Generated by Django 4.0.2 on 2022-06-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_rename_category_productcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productcrawllog',
            options={'verbose_name_plural': 'Product Crawl Logs'},
        ),
        migrations.AlterModelOptions(
            name='productpricelog',
            options={'verbose_name_plural': 'Product Price Logs'},
        ),
        migrations.AlterModelOptions(
            name='productview',
            options={'verbose_name_plural': 'Product Views'},
        ),
    ]
