# Generated by Django 4.0.5 on 2022-06-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_categories', '0001_initial'),
        ('shops', '0007_alter_shopworkfield_category'),
        ('products', '0023_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='product_categories.productcategory'),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
