# Generated by Django 4.0.5 on 2022-07-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_product_categories_delete_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
