# Generated by Django 4.0.5 on 2022-07-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_product_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_key',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
