# Generated by Django 4.0.5 on 2022-07-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productlinkview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='need_crawl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('deleted', 'Deleted')], default='published', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=1024, unique=True),
        ),
    ]
