# Generated by Django 4.0.6 on 2022-07-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_product_need_crawl_product_status_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcrawllog',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Product Crawl Logs'},
        ),
        migrations.AlterModelOptions(
            name='productlinkview',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Product Link Views'},
        ),
        migrations.AlterModelOptions(
            name='productpricelog',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Product Price Logs'},
        ),
        migrations.AlterModelOptions(
            name='productview',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Product Views'},
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Deleted', 'Deleted')], default='Published', max_length=32),
        ),
    ]
